### ISSUE TITLE
Error when inference

### ISSUE THREAD

**Issue by godspirit00** [keonlee9420/Daft-Exprt#6]
Hello! Thanks for the amazing work!
I'm meeting something wrong when inference:
```
FileNotFoundError: [Errno 2] No such file or directory: './preprocessed_data/VCTK/spker_embed/p317-spker_embed.npy'
```
What am I missing? 
Thanks!

**Comment by keonlee9420** [comment]
Hi @godspirit00 , thanks for your attention. It is because you don't have speaker embeddings. You need to get speaker embeddings beforehand(please check `preprocess.yaml` and `preprocess.py`). The other way is to modify the current `synthesize.py` to extract speaker embedding using **DeepSpeaker** at inference time.

**Comment by godspirit00** [comment]
Thanks for the reply! I will have a try. 
Thanks again!
