### ISSUE TITLE
Unseen Speaker Synthesis

### ISSUE THREAD

**Issue by migi-gon** [keonlee9420/Daft-Exprt#8]
Hello!
Would you be able to synthesize speech using speakers not used during the training? ie. load the unseen speaker's embeddings during inference

I think by changing this particular line in synthesize.py:
```
spker_embeds = np.load(os.path.join(
            preprocess_config["path"]["preprocessed_path"],
            "spker_embed",
            "{}-spker_embed.npy".format(args.speaker_id),
        )) if load_spker_embed else None
```

However, I'm not sure if it is wise to do this and would result to poor quality. Have you tried doing this?

**Comment by keonlee9420** [comment]
Hi @migi-gon , thanks for your attention. First of all, the best way would be to apply additional speaker modelings. One of the recent work regarding to this is Speaker Generation from google, which generates new speaker by interpolating learned speakers (embeddings). Check out [the paper](https://arxiv.org/abs/2111.05095)!

But without any additional implementation, you can try as follows:
1. Theoretically, you can generate new speaker by averaging two speaker embedding of this repo. For example, you can input (`spker_embeds_1` + `spker_embeds_2`) / 2 to the model and expect the output speech have the speaker identity somewhere in between speaker 1 and speaker 2. `spker_embeds_1` and `spker_embeds_2` are loaded by the line that you mentioned above. But this would not always work since we didn't have any constraint on the speaker embeddings to be lying on the linear space.
3. Another way is extracting new embedding by the same embedder from an audio of target speaker (DeepSpeaker in our implementation) and then inputting it to the model. But still, this will not work very well since we didn't have any constraints on the speaker embedding space to be aligned with DeepSpeaker embedder's embedding space.

**Comment by keonlee9420** [comment]
Close due to inactivity.
